$(document).ready(function(){
    $("#btn1").hide();
    $(".column1").mouseout(function(){
        $("#btn1").hide();
    })
    $(".column1").mouseover(function(){
        $("#btn1").show();
    })
    $("#btn2").hide();
    $(".column2").mouseout(function(){
        $("#btn2").hide();
    })
    $(".column2").mouseover(function(){
        $("#btn2").show();
    })
    $("#btn3").hide();
    $(".column3").mouseout(function(){
        $("#btn3").hide();
    })
    $(".column3").mouseover(function(){
        $("#btn3").show();
    })
    $("#btn4").hide();
    $(".column4").mouseout(function(){
        $("#btn4").hide();
    })
    $(".column4").mouseover(function(){
        $("#btn4").show();
    })
    $("#btn5").hide();
    $(".column5").mouseout(function(){
        $("#btn5").hide();
    })
    $(".column5").mouseover(function(){
        $("#btn5").show();
    })
    $("#btn6").hide();
    $(".column6").mouseout(function(){
        $("#btn6").hide();
    })
    $(".column6").mouseover(function(){
        $("#btn6").show();
    })
})